// Major international airports for FlyAndEarn
const AIRPORTS = [
  // Europe
  { code: 'WAW', city: 'Warsaw', country: 'Poland', name: 'Warsaw Chopin' },
  { code: 'KRK', city: 'Krakow', country: 'Poland', name: 'Krakow John Paul II' },
  { code: 'GDN', city: 'Gdansk', country: 'Poland', name: 'Gdansk Lech Walesa' },
  { code: 'WRO', city: 'Wroclaw', country: 'Poland', name: 'Wroclaw Copernicus' },
  { code: 'POZ', city: 'Poznan', country: 'Poland', name: 'Poznan Lawica' },
  { code: 'LHR', city: 'London', country: 'UK', name: 'London Heathrow' },
  { code: 'LGW', city: 'London', country: 'UK', name: 'London Gatwick' },
  { code: 'STN', city: 'London', country: 'UK', name: 'London Stansted' },
  { code: 'LTN', city: 'London', country: 'UK', name: 'London Luton' },
  { code: 'CDG', city: 'Paris', country: 'France', name: 'Paris Charles de Gaulle' },
  { code: 'ORY', city: 'Paris', country: 'France', name: 'Paris Orly' },
  { code: 'FRA', city: 'Frankfurt', country: 'Germany', name: 'Frankfurt am Main' },
  { code: 'MUC', city: 'Munich', country: 'Germany', name: 'Munich' },
  { code: 'BER', city: 'Berlin', country: 'Germany', name: 'Berlin Brandenburg' },
  { code: 'DUS', city: 'Dusseldorf', country: 'Germany', name: 'Dusseldorf' },
  { code: 'HAM', city: 'Hamburg', country: 'Germany', name: 'Hamburg' },
  { code: 'AMS', city: 'Amsterdam', country: 'Netherlands', name: 'Amsterdam Schiphol' },
  { code: 'BRU', city: 'Brussels', country: 'Belgium', name: 'Brussels' },
  { code: 'MAD', city: 'Madrid', country: 'Spain', name: 'Madrid Barajas' },
  { code: 'BCN', city: 'Barcelona', country: 'Spain', name: 'Barcelona El Prat' },
  { code: 'FCO', city: 'Rome', country: 'Italy', name: 'Rome Fiumicino' },
  { code: 'MXP', city: 'Milan', country: 'Italy', name: 'Milan Malpensa' },
  { code: 'VCE', city: 'Venice', country: 'Italy', name: 'Venice Marco Polo' },
  { code: 'VIE', city: 'Vienna', country: 'Austria', name: 'Vienna' },
  { code: 'ZRH', city: 'Zurich', country: 'Switzerland', name: 'Zurich' },
  { code: 'GVA', city: 'Geneva', country: 'Switzerland', name: 'Geneva' },
  { code: 'CPH', city: 'Copenhagen', country: 'Denmark', name: 'Copenhagen' },
  { code: 'OSL', city: 'Oslo', country: 'Norway', name: 'Oslo Gardermoen' },
  { code: 'ARN', city: 'Stockholm', country: 'Sweden', name: 'Stockholm Arlanda' },
  { code: 'HEL', city: 'Helsinki', country: 'Finland', name: 'Helsinki Vantaa' },
  { code: 'PRG', city: 'Prague', country: 'Czech Republic', name: 'Prague Vaclav Havel' },
  { code: 'BUD', city: 'Budapest', country: 'Hungary', name: 'Budapest Ferenc Liszt' },
  { code: 'ATH', city: 'Athens', country: 'Greece', name: 'Athens Eleftherios Venizelos' },
  { code: 'LIS', city: 'Lisbon', country: 'Portugal', name: 'Lisbon Humberto Delgado' },
  { code: 'DUB', city: 'Dublin', country: 'Ireland', name: 'Dublin' },
  { code: 'IST', city: 'Istanbul', country: 'Turkey', name: 'Istanbul' },

  // Middle East
  { code: 'DXB', city: 'Dubai', country: 'UAE', name: 'Dubai International' },
  { code: 'DWC', city: 'Dubai', country: 'UAE', name: 'Al Maktoum' },
  { code: 'AUH', city: 'Abu Dhabi', country: 'UAE', name: 'Abu Dhabi' },
  { code: 'DOH', city: 'Doha', country: 'Qatar', name: 'Hamad International' },
  { code: 'RUH', city: 'Riyadh', country: 'Saudi Arabia', name: 'King Khalid' },
  { code: 'JED', city: 'Jeddah', country: 'Saudi Arabia', name: 'King Abdulaziz' },
  { code: 'DMM', city: 'Dammam', country: 'Saudi Arabia', name: 'King Fahd' },
  { code: 'KWI', city: 'Kuwait City', country: 'Kuwait', name: 'Kuwait International' },
  { code: 'BAH', city: 'Bahrain', country: 'Bahrain', name: 'Bahrain International' },
  { code: 'MCT', city: 'Muscat', country: 'Oman', name: 'Muscat International' },
  { code: 'TLV', city: 'Tel Aviv', country: 'Israel', name: 'Ben Gurion' },
  { code: 'AMM', city: 'Amman', country: 'Jordan', name: 'Queen Alia' },
  { code: 'BEY', city: 'Beirut', country: 'Lebanon', name: 'Rafic Hariri' },
  { code: 'CAI', city: 'Cairo', country: 'Egypt', name: 'Cairo International' },
  { code: 'IKA', city: 'Tehran', country: 'Iran', name: 'Imam Khomeini' },
  { code: 'BGW', city: 'Baghdad', country: 'Iraq', name: 'Baghdad International' },

  // Asia
  { code: 'SIN', city: 'Singapore', country: 'Singapore', name: 'Singapore Changi' },
  { code: 'HKG', city: 'Hong Kong', country: 'Hong Kong', name: 'Hong Kong International' },
  { code: 'BKK', city: 'Bangkok', country: 'Thailand', name: 'Suvarnabhumi' },
  { code: 'DMK', city: 'Bangkok', country: 'Thailand', name: 'Don Mueang' },
  { code: 'KUL', city: 'Kuala Lumpur', country: 'Malaysia', name: 'Kuala Lumpur International' },
  { code: 'NRT', city: 'Tokyo', country: 'Japan', name: 'Tokyo Narita' },
  { code: 'HND', city: 'Tokyo', country: 'Japan', name: 'Tokyo Haneda' },
  { code: 'KIX', city: 'Osaka', country: 'Japan', name: 'Kansai International' },
  { code: 'ICN', city: 'Seoul', country: 'South Korea', name: 'Incheon' },
  { code: 'GMP', city: 'Seoul', country: 'South Korea', name: 'Gimpo' },
  { code: 'PEK', city: 'Beijing', country: 'China', name: 'Beijing Capital' },
  { code: 'PKX', city: 'Beijing', country: 'China', name: 'Beijing Daxing' },
  { code: 'PVG', city: 'Shanghai', country: 'China', name: 'Shanghai Pudong' },
  { code: 'SHA', city: 'Shanghai', country: 'China', name: 'Shanghai Hongqiao' },
  { code: 'CAN', city: 'Guangzhou', country: 'China', name: 'Guangzhou Baiyun' },
  { code: 'SZX', city: 'Shenzhen', country: 'China', name: 'Shenzhen Baoan' },
  { code: 'CTU', city: 'Chengdu', country: 'China', name: 'Chengdu Tianfu' },
  { code: 'DEL', city: 'New Delhi', country: 'India', name: 'Indira Gandhi' },
  { code: 'BOM', city: 'Mumbai', country: 'India', name: 'Chhatrapati Shivaji' },
  { code: 'BLR', city: 'Bangalore', country: 'India', name: 'Kempegowda' },
  { code: 'MAA', city: 'Chennai', country: 'India', name: 'Chennai International' },
  { code: 'CCU', city: 'Kolkata', country: 'India', name: 'Netaji Subhas Chandra Bose' },
  { code: 'HYD', city: 'Hyderabad', country: 'India', name: 'Rajiv Gandhi' },
  { code: 'MNL', city: 'Manila', country: 'Philippines', name: 'Ninoy Aquino' },
  { code: 'CEB', city: 'Cebu', country: 'Philippines', name: 'Mactan-Cebu' },
  { code: 'DVO', city: 'Davao', country: 'Philippines', name: 'Francisco Bangoy' },
  { code: 'CGK', city: 'Jakarta', country: 'Indonesia', name: 'Soekarno-Hatta' },
  { code: 'DPS', city: 'Bali', country: 'Indonesia', name: 'Ngurah Rai' },
  { code: 'SUB', city: 'Surabaya', country: 'Indonesia', name: 'Juanda' },
  { code: 'SGN', city: 'Ho Chi Minh City', country: 'Vietnam', name: 'Tan Son Nhat' },
  { code: 'HAN', city: 'Hanoi', country: 'Vietnam', name: 'Noi Bai' },
  { code: 'DAD', city: 'Da Nang', country: 'Vietnam', name: 'Da Nang International' },
  { code: 'RGN', city: 'Yangon', country: 'Myanmar', name: 'Yangon International' },
  { code: 'CMB', city: 'Colombo', country: 'Sri Lanka', name: 'Bandaranaike' },
  { code: 'DAC', city: 'Dhaka', country: 'Bangladesh', name: 'Hazrat Shahjalal' },
  { code: 'KTM', city: 'Kathmandu', country: 'Nepal', name: 'Tribhuvan' },
  { code: 'MLE', city: 'Male', country: 'Maldives', name: 'Velana International' },
  { code: 'PNH', city: 'Phnom Penh', country: 'Cambodia', name: 'Phnom Penh International' },
  { code: 'REP', city: 'Siem Reap', country: 'Cambodia', name: 'Siem Reap International' },
  { code: 'VTE', city: 'Vientiane', country: 'Laos', name: 'Wattay International' },
  { code: 'TPE', city: 'Taipei', country: 'Taiwan', name: 'Taiwan Taoyuan' },
  { code: 'TSA', city: 'Taipei', country: 'Taiwan', name: 'Taipei Songshan' },
  { code: 'MFM', city: 'Macau', country: 'Macau', name: 'Macau International' },

  // Americas
  { code: 'JFK', city: 'New York', country: 'USA', name: 'John F. Kennedy' },
  { code: 'EWR', city: 'Newark', country: 'USA', name: 'Newark Liberty' },
  { code: 'LGA', city: 'New York', country: 'USA', name: 'LaGuardia' },
  { code: 'LAX', city: 'Los Angeles', country: 'USA', name: 'Los Angeles International' },
  { code: 'ORD', city: 'Chicago', country: 'USA', name: 'Chicago O\'Hare' },
  { code: 'MDW', city: 'Chicago', country: 'USA', name: 'Chicago Midway' },
  { code: 'MIA', city: 'Miami', country: 'USA', name: 'Miami International' },
  { code: 'FLL', city: 'Fort Lauderdale', country: 'USA', name: 'Fort Lauderdale-Hollywood' },
  { code: 'SFO', city: 'San Francisco', country: 'USA', name: 'San Francisco International' },
  { code: 'OAK', city: 'Oakland', country: 'USA', name: 'Oakland International' },
  { code: 'SJC', city: 'San Jose', country: 'USA', name: 'San Jose International' },
  { code: 'ATL', city: 'Atlanta', country: 'USA', name: 'Hartsfield-Jackson' },
  { code: 'DFW', city: 'Dallas', country: 'USA', name: 'Dallas/Fort Worth' },
  { code: 'IAH', city: 'Houston', country: 'USA', name: 'George Bush Intercontinental' },
  { code: 'DEN', city: 'Denver', country: 'USA', name: 'Denver International' },
  { code: 'SEA', city: 'Seattle', country: 'USA', name: 'Seattle-Tacoma' },
  { code: 'PHX', city: 'Phoenix', country: 'USA', name: 'Phoenix Sky Harbor' },
  { code: 'LAS', city: 'Las Vegas', country: 'USA', name: 'Harry Reid International' },
  { code: 'BOS', city: 'Boston', country: 'USA', name: 'Boston Logan' },
  { code: 'MSP', city: 'Minneapolis', country: 'USA', name: 'Minneapolis-St. Paul' },
  { code: 'DTW', city: 'Detroit', country: 'USA', name: 'Detroit Metropolitan' },
  { code: 'PHL', city: 'Philadelphia', country: 'USA', name: 'Philadelphia International' },
  { code: 'CLT', city: 'Charlotte', country: 'USA', name: 'Charlotte Douglas' },
  { code: 'MCO', city: 'Orlando', country: 'USA', name: 'Orlando International' },
  { code: 'SAN', city: 'San Diego', country: 'USA', name: 'San Diego International' },
  { code: 'HNL', city: 'Honolulu', country: 'USA', name: 'Daniel K. Inouye' },
  { code: 'YYZ', city: 'Toronto', country: 'Canada', name: 'Toronto Pearson' },
  { code: 'YVR', city: 'Vancouver', country: 'Canada', name: 'Vancouver International' },
  { code: 'YUL', city: 'Montreal', country: 'Canada', name: 'Montreal-Trudeau' },
  { code: 'YYC', city: 'Calgary', country: 'Canada', name: 'Calgary International' },
  { code: 'YOW', city: 'Ottawa', country: 'Canada', name: 'Ottawa Macdonald-Cartier' },
  { code: 'MEX', city: 'Mexico City', country: 'Mexico', name: 'Benito Juarez' },
  { code: 'CUN', city: 'Cancun', country: 'Mexico', name: 'Cancun International' },
  { code: 'GDL', city: 'Guadalajara', country: 'Mexico', name: 'Miguel Hidalgo y Costilla' },
  { code: 'GRU', city: 'Sao Paulo', country: 'Brazil', name: 'Guarulhos' },
  { code: 'GIG', city: 'Rio de Janeiro', country: 'Brazil', name: 'Galeao' },
  { code: 'BSB', city: 'Brasilia', country: 'Brazil', name: 'Presidente Juscelino Kubitschek' },
  { code: 'EZE', city: 'Buenos Aires', country: 'Argentina', name: 'Ezeiza' },
  { code: 'AEP', city: 'Buenos Aires', country: 'Argentina', name: 'Aeroparque Jorge Newbery' },
  { code: 'SCL', city: 'Santiago', country: 'Chile', name: 'Arturo Merino Benitez' },
  { code: 'LIM', city: 'Lima', country: 'Peru', name: 'Jorge Chavez' },
  { code: 'BOG', city: 'Bogota', country: 'Colombia', name: 'El Dorado' },
  { code: 'MDE', city: 'Medellin', country: 'Colombia', name: 'Jose Maria Cordova' },
  { code: 'PTY', city: 'Panama City', country: 'Panama', name: 'Tocumen International' },
  { code: 'SJO', city: 'San Jose', country: 'Costa Rica', name: 'Juan Santamaria' },
  { code: 'HAV', city: 'Havana', country: 'Cuba', name: 'Jose Marti' },
  { code: 'SJU', city: 'San Juan', country: 'Puerto Rico', name: 'Luis Munoz Marin' },
  { code: 'NAS', city: 'Nassau', country: 'Bahamas', name: 'Lynden Pindling' },
  { code: 'MBJ', city: 'Montego Bay', country: 'Jamaica', name: 'Sangster International' },
  { code: 'PUJ', city: 'Punta Cana', country: 'Dominican Republic', name: 'Punta Cana International' },

  // Africa
  { code: 'JNB', city: 'Johannesburg', country: 'South Africa', name: 'O.R. Tambo' },
  { code: 'CPT', city: 'Cape Town', country: 'South Africa', name: 'Cape Town International' },
  { code: 'DUR', city: 'Durban', country: 'South Africa', name: 'King Shaka' },
  { code: 'NBO', city: 'Nairobi', country: 'Kenya', name: 'Jomo Kenyatta' },
  { code: 'MBA', city: 'Mombasa', country: 'Kenya', name: 'Moi International' },
  { code: 'ADD', city: 'Addis Ababa', country: 'Ethiopia', name: 'Bole International' },
  { code: 'LOS', city: 'Lagos', country: 'Nigeria', name: 'Murtala Muhammed' },
  { code: 'ABV', city: 'Abuja', country: 'Nigeria', name: 'Nnamdi Azikiwe' },
  { code: 'ACC', city: 'Accra', country: 'Ghana', name: 'Kotoka International' },
  { code: 'CMN', city: 'Casablanca', country: 'Morocco', name: 'Mohammed V' },
  { code: 'RAK', city: 'Marrakech', country: 'Morocco', name: 'Menara' },
  { code: 'TUN', city: 'Tunis', country: 'Tunisia', name: 'Tunis-Carthage' },
  { code: 'ALG', city: 'Algiers', country: 'Algeria', name: 'Houari Boumediene' },
  { code: 'DSS', city: 'Dakar', country: 'Senegal', name: 'Blaise Diagne' },
  { code: 'DAR', city: 'Dar es Salaam', country: 'Tanzania', name: 'Julius Nyerere' },
  { code: 'ZNZ', city: 'Zanzibar', country: 'Tanzania', name: 'Abeid Amani Karume' },
  { code: 'EBB', city: 'Entebbe', country: 'Uganda', name: 'Entebbe International' },
  { code: 'KGL', city: 'Kigali', country: 'Rwanda', name: 'Kigali International' },
  { code: 'MRU', city: 'Mauritius', country: 'Mauritius', name: 'Sir Seewoosagur Ramgoolam' },
  { code: 'SEZ', city: 'Mahe', country: 'Seychelles', name: 'Seychelles International' },
  { code: 'TNR', city: 'Antananarivo', country: 'Madagascar', name: 'Ivato International' },
  { code: 'HRE', city: 'Harare', country: 'Zimbabwe', name: 'Robert Gabriel Mugabe' },
  { code: 'LUN', city: 'Lusaka', country: 'Zambia', name: 'Kenneth Kaunda' },
  { code: 'WDH', city: 'Windhoek', country: 'Namibia', name: 'Hosea Kutako' },
  { code: 'GBE', city: 'Gaborone', country: 'Botswana', name: 'Sir Seretse Khama' },
  { code: 'MPM', city: 'Maputo', country: 'Mozambique', name: 'Maputo International' },

  // Oceania
  { code: 'SYD', city: 'Sydney', country: 'Australia', name: 'Sydney Kingsford Smith' },
  { code: 'MEL', city: 'Melbourne', country: 'Australia', name: 'Melbourne Tullamarine' },
  { code: 'BNE', city: 'Brisbane', country: 'Australia', name: 'Brisbane Airport' },
  { code: 'PER', city: 'Perth', country: 'Australia', name: 'Perth Airport' },
  { code: 'ADL', city: 'Adelaide', country: 'Australia', name: 'Adelaide Airport' },
  { code: 'CNS', city: 'Cairns', country: 'Australia', name: 'Cairns Airport' },
  { code: 'OOL', city: 'Gold Coast', country: 'Australia', name: 'Gold Coast Airport' },
  { code: 'AKL', city: 'Auckland', country: 'New Zealand', name: 'Auckland' },
  { code: 'WLG', city: 'Wellington', country: 'New Zealand', name: 'Wellington International' },
  { code: 'CHC', city: 'Christchurch', country: 'New Zealand', name: 'Christchurch International' },
  { code: 'ZQN', city: 'Queenstown', country: 'New Zealand', name: 'Queenstown Airport' },
  { code: 'NAN', city: 'Nadi', country: 'Fiji', name: 'Nadi International' },
  { code: 'PPT', city: 'Papeete', country: 'French Polynesia', name: 'Faaa International' },
  { code: 'GUM', city: 'Guam', country: 'Guam', name: 'Antonio B. Won Pat' },
  { code: 'NOU', city: 'Noumea', country: 'New Caledonia', name: 'La Tontouta' }
];

// Group airports by region for organized display
const AIRPORT_REGIONS = {
  'Europe': ['WAW', 'KRK', 'GDN', 'WRO', 'POZ', 'LHR', 'LGW', 'STN', 'LTN', 'CDG', 'ORY', 'FRA', 'MUC', 'BER', 'DUS', 'HAM', 'AMS', 'BRU', 'MAD', 'BCN', 'FCO', 'MXP', 'VCE', 'VIE', 'ZRH', 'GVA', 'CPH', 'OSL', 'ARN', 'HEL', 'PRG', 'BUD', 'ATH', 'LIS', 'DUB', 'IST'],
  'Middle East': ['DXB', 'DWC', 'AUH', 'DOH', 'RUH', 'JED', 'DMM', 'KWI', 'BAH', 'MCT', 'TLV', 'AMM', 'BEY', 'CAI', 'IKA', 'BGW'],
  'Asia': ['SIN', 'HKG', 'BKK', 'DMK', 'KUL', 'NRT', 'HND', 'KIX', 'ICN', 'GMP', 'PEK', 'PKX', 'PVG', 'SHA', 'CAN', 'SZX', 'CTU', 'DEL', 'BOM', 'BLR', 'MAA', 'CCU', 'HYD', 'MNL', 'CEB', 'DVO', 'CGK', 'DPS', 'SUB', 'SGN', 'HAN', 'DAD', 'RGN', 'CMB', 'DAC', 'KTM', 'MLE', 'PNH', 'REP', 'VTE', 'TPE', 'TSA', 'MFM'],
  'Americas': ['JFK', 'EWR', 'LGA', 'LAX', 'ORD', 'MDW', 'MIA', 'FLL', 'SFO', 'OAK', 'SJC', 'ATL', 'DFW', 'IAH', 'DEN', 'SEA', 'PHX', 'LAS', 'BOS', 'MSP', 'DTW', 'PHL', 'CLT', 'MCO', 'SAN', 'HNL', 'YYZ', 'YVR', 'YUL', 'YYC', 'YOW', 'MEX', 'CUN', 'GDL', 'GRU', 'GIG', 'BSB', 'EZE', 'AEP', 'SCL', 'LIM', 'BOG', 'MDE', 'PTY', 'SJO', 'HAV', 'SJU', 'NAS', 'MBJ', 'PUJ'],
  'Africa': ['JNB', 'CPT', 'DUR', 'NBO', 'MBA', 'ADD', 'LOS', 'ABV', 'ACC', 'CMN', 'RAK', 'TUN', 'ALG', 'DSS', 'DAR', 'ZNZ', 'EBB', 'KGL', 'MRU', 'SEZ', 'TNR', 'HRE', 'LUN', 'WDH', 'GBE', 'MPM'],
  'Oceania': ['SYD', 'MEL', 'BNE', 'PER', 'ADL', 'CNS', 'OOL', 'AKL', 'WLG', 'CHC', 'ZQN', 'NAN', 'PPT', 'GUM', 'NOU']
};

// Helper functions
function getAirportByCode(code) {
  return AIRPORTS.find(a => a.code === code);
}

function searchAirports(query) {
  if (!query || query.length < 2) return [];
  const q = query.toLowerCase();
  return AIRPORTS.filter(a =>
    a.code.toLowerCase().includes(q) ||
    a.city.toLowerCase().includes(q) ||
    a.country.toLowerCase().includes(q) ||
    a.name.toLowerCase().includes(q)
  ).slice(0, 15);
}

function formatAirportOption(airport) {
  return `${airport.code} - ${airport.city}, ${airport.country}`;
}
